### ISSUE TITLE
Custom audiofile for slides

### ISSUE THREAD

**Issue by hearth1an** [xen-42/outer-wilds-new-horizons#229] opened 2022-07-11 16:56 UTC
### Feature

It would be nice if backdropAudio could load mp3 or wav sound from folder

**Comment by dgarroDC** [comment] 2022-07-12 23:22
This is a duplicate of #118

**Comment by xen-42** [comment] 2022-07-14 03:49
Done in 1.4.0

**Closed by xen-42** 2022-07-14 03:49 UTC
Labels: feature
