### ISSUE TITLE
Warping seems to break completely in NomaiVR

### ISSUE THREAD

**Issue by SpencerMeow** [xen-42/outer-wilds-new-horizons#18] opened 2022-01-15 23:19 UTC
I was trying to use 2 mods (seperately) in NomaiVR today, Outer Wilds Galaxy, and Gargantua/Interstellar, but when I enter any warp it just is stuck on black and all I can hear is the purple gravity elevator noise on loop, and the headset latency goes crazy high.

**Comment by xen-42** [comment] 2022-01-16 18:42
Can you share the logs from the mod manager please

**Comment by SpencerMeow** [comment] 2022-01-25 02:24
> 

Hey I'm really sorry for the late response,  here is the logs
[OWML.Log.24-01-2022-20.16.47.txt](https://github.com/xen-42/outer-wilds-new-horizons/files/7930135/OWML.Log.24-01-2022-20.16.47.txt)

**Comment by xen-42** [comment] 2022-03-21 05:18
This should be fixed by now (assuming this was caused by the dreaded warp bug)

**Closed by xen-42** 2022-03-21 05:18 UTC
