### ISSUE TITLE
Cloaks Goofy

### ISSUE THREAD

**Issue by JohnCorby** [xen-42/outer-wilds-new-horizons#157] opened 2022-05-25 21:26 UTC
they suck, only one works at a time, and the transition is broken (even for the one that should be working)

**Comment by JohnCorby** [comment] 2022-06-13 22:05
okay now the thing that has the cloak does work, but the issue still persists that only one thing will have a cloak

**Comment by xen-42** [comment] 2022-06-13 22:06
Last bit was fixed by MegaPiggy, rest is a duplicate of #108

**Closed** 2022-06-13 22:06 UTC
